version: '3'
services:
    mysql:
        image: mysql:5.7
        hostname: mysql
        environment:
                HOSTNAME: mysql
                MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
                MYSQL_DATABASE: ${MYSQL_DATABASE}
                MYSQL_USER: ${MYSQL_USER}
                MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
                - "3306:3306"
    web:
        image: nginx:latest
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        environment:
                MYSQL_USER: ${MYSQL_USER}
                MYSQL_PASSWORD: ${MYSQL_PASSWORD}
                HOST: mysql
        ports:
                - 8080:80
        volumes:
                - ./service1/nginx/nginx.conf:/etc/nginx/conf.d/default.template
        depends_on:
            - php
    php:
        build: ./service1
        image: php:service1
        restart: always
    web2:
        image: nginx:latest
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        environment:
                MYSQL_USER: ${MYSQL_USER}
                MYSQL_PASSWORD: ${MYSQL_PASSWORD}
                HOST: mysql
        ports:
                - 8081:80
        volumes:
                - ./service2/nginx2/nginx.conf:/etc/nginx/conf.d/default.template
        depends_on:
                - php2

    php2:
        build: ./service2
        image: php:service2
        restart: always
    web3:
        image: nginx:latest
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        environment:
                MYSQL_USER: ${MYSQL_USER}
                MYSQL_PASSWORD: ${MYSQL_PASSWORD}
                HOST: mysql
        ports:
                - 8082:80
        volumes:
                - ./service3/nginx3/nginx.conf:/etc/nginx/conf.d/default.template
        depends_on:
                - php3

    php3:
        build: ./service3
        image: php:service3
        restart: always
