version: '3'
services:
    web:
        image: nginx-service
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        environment:
                MYSQL_USER: devuser
                MYSQL_PASSWORD: devpass
        ports:
                - 8082:80
        
        depends_on:
            - php
            - mysql
              #    php:
              #image: php
              #restart: always
              # ports:
              #  - 9000:9000
    php:
        image: php
        restart: always
        # ports:
                # - 8081:8081
    mysql:
        image: mysql:5.7
        hostname: mysql
        environment:
                HOSTNAME: mysql
                MYSQL_ROOT_PASSWORD: my_secret_pw_shh
                MYSQL_DATABASE: test_db
                MYSQL_USER: devuser
                MYSQL_PASSWORD: devpass
        ports:
                - "3306:3306"
